upstream rails_app {
  server app:3000;
}

server {
  listen 80;
  server_name fundacionlatortuga.com www.fundacionlatortuga.com;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name fundacionlatortuga.com www.fundacionlatortuga.com;

  ssl_certificate     /etc/nginx/ssl/fullchain.pem;
  ssl_certificate_key /etc/nginx/ssl/privkey.pem;
  ssl_dhparam         /etc/nginx/ssl/ssl-dhparams.pem;

  ssl_protocols             TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  location /assets/ {
    alias /app/public/assets/;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location / {
    proxy_pass http://rails_app;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    client_max_body_size 4G;
    keepalive_timeout 10;
  }
}